thoth-station/prescriptions

prescription.yaml

This is an initial import of all the units already available in Python implementation. Rewritted to YAML supporting prescriptions v1 schema.

Initial import of units already implemented in Python

---

prescription.yaml

Related: https://github.com/thoth-station/adviser/pull/1779

Add name of the prescription

---

prescription.yaml

Related: https://github.com/thoth-station/adviser/pull/1796

MKL threads wrap prescription

---

prescription.yaml

Related: https://github.com/thoth-station/adviser/pull/1799

Add wrap notifying about slow TF Keras embedding

---

prescription.yaml

Related: https://github.com/tensorflow/tensorflow/issues/41827

Notify about performance degradation in dataset batch

---

prescription.yaml

Related: https://github.com/thoth-station/adviser/pull/1806

Use new schema for match and run

---

prescription.yaml

fix module name

---

.aicoe-ci.yaml

Related: https://github.com/thoth-station/adviser/issues/1908

Add AICoE-CI configuration to build this repo as a container image

---

.aicoe-ci.yaml

Related: https://github.com/thoth-station/thoth-application/pull/1694/

Point AICoE CI to adviser imagestreams in thoth-application

---

prescriptions/gitpython/rpm.yaml

Require Git present when GitPython package is installed.

GitPython is a Python wrapper for Git 

---

prescriptions/tensorflow/tf_onednn_env.yaml

See: https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0

Add justification for enabling oneDNN opts

---

prescriptions/tensorflow/tf_22_ptxas.yaml

Related: https://github.com/tensorflow/tensorflow/issues/40036

Notify about performance degradation if ptxas are not available

---

prescriptions/pi_/pillow/pillow830_typeerror.yaml

Closes: https://github.com/thoth-station/prescriptions/pull/49

Add prescription for Pillow==8.3.0 and NumPy incompatibilities

---

prescriptions/_generic/no_cpu.yaml

Warn users if no CPU information is supplied

---

prescriptions/_generic/recommendation_types.yaml

Notify users about recommendation type used

---

prescriptions/_generic/so_python_36_tags.yaml
prescriptions/_generic/so_python_37_tags.yaml
prescriptions/_generic/so_python_38_tags.yaml
prescriptions/_generic/so_python_39_tags.yaml

/kind feature
Related: https://github.com/thoth-station/prescriptions/issues/73

Add pipeline units that point to Python tags on StackOverflow

---

prescriptions/te_/tensorflow/tf_cudnn.yaml

See https://www.tensorflow.org/install/source#gpu

Resolve TensorFlow considering cuDNN version available

---

prescriptions/_security_warnings/multiprocessing_pickle.yaml

See docs: https://docs.python.org/3.11/library/multiprocessing.html#multiprocessing-recv-pickle-security

Fix library usage for multiprocessing pickle

---

prescriptions/te_/tensorflow/tf_cuda_cudnnn.yaml

See compatibility table: https://www.tensorflow.org/install/source#gpu

Produce warnings if users use unsupported cuDNN and CUDA versions with TensorFlow

---

prescriptions/to_/torch-model-archiver/cpu_index.yaml
prescriptions/to_/torch-model-archiver/gpu_index.yaml
prescriptions/to_/torch-model-archiver/no_cuda.yaml
prescriptions/to_/torch-model-archiver/no_cuda_match.yaml
prescriptions/to_/torch-tb-profiler/cpu_index.yaml
prescriptions/to_/torch-tb-profiler/gpu_index.yaml
prescriptions/to_/torch/cpu_index.yaml
prescriptions/to_/torch/gpu_index.yaml
prescriptions/to_/torchaudio/cpu_index.yaml
prescriptions/to_/torchaudio/gpu_index.yaml
prescriptions/to_/torchcsprng/cpu_index.yaml
prescriptions/to_/torchcsprng/gpu_index.yaml
prescriptions/to_/torchserve/cpu_index.yaml
prescriptions/to_/torchserve/gpu_index.yaml
prescriptions/to_/torchtext/cpu_index.yaml
prescriptions/to_/torchtext/gpu_index.yaml
prescriptions/to_/torchvision/cpu_index.yaml
prescriptions/to_/torchvision/gpu_index.yaml

See https://github.com/thoth-station/thoth-application/issues/632#issuecomment-896748208

Add units specific to torch package index

---

prescriptions/nu_/numpy/np_random.yaml

See https://numpy.org/neps/nep-0019-rng-policy.html#numpy-random

Point users to NEP-19 if they use NumPy's random generator

---

prescriptions/nu_/numpy/np_support.yaml

Closes: https://github.com/thoth-station/adviser/issues/1268

Notify if a no longer supported NumPy is used

---

prescriptions/nu_/numpy/np_py_support.yaml

See https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table
Closes: https://github.com/thoth-station/adviser/issues/1268

Add prescriptions related to supported NumPy's Python version

---

prescriptions/te_/tensorflow/tf_rm_scipy.yaml

Related: https://github.com/thoth-station/adviser/pull/2059

Correctly skip SciPy accidentally included by TensorFlow

---

prescriptions/te_/tensorflow/tf_gpu.yaml

Related: https://github.com/thoth-station/adviser/pull/2062/

Suggest to use tensorflow-gpu for CUDA/cuDNN enabled environments

---

prescriptions/_library/deprecated.yaml

Notify about deprecated parts of the standard library

---

prescriptions/in_/injector/security_scorecards_signed_releases.yaml

💊 Signed-Releases Security Scorecards update for 'injector'

---

prescriptions/in_/injector/score_cards_automatic_dependency_update.yaml

💊 Automatic-Dependency-Update Security Scorecards update for 'injector'

---

prescriptions/in_/injector/score_cards_active.yaml

💊 Active Security Scorecards update for 'injector'

---

prescriptions/in_/injector/security_scorecards_ci_tests.yaml

💊 CI-Tests Security Scorecards update for 'injector'

---

prescriptions/in_/injector/security_scorecards_sast.yaml

💊 SAST Security Scorecards update for 'injector'

---

prescriptions/in_/inflection/security_scorecards_security_policy.yaml

💊 Security-Policy Security Scorecards update for 'inflection'

---

prescriptions/in_/inflection/security_scorecards_packaging.yaml

💊 Packaging Security Scorecards update for 'inflection'

---

prescriptions/in_/injector/security_scorecards_token_permissions.yaml

💊 Token-Permissions Security Scorecards update for 'injector'

---

prescriptions/du_/dulwich/gh_link.yaml

💊 Package 'dulwich' is hosted on GitHub

---

prescriptions/sa_/sanic/score_cards_automatic_dependency_update.yaml

💊 Automatic-Dependency-Update Security Scorecards update for 'sanic'

---

prescriptions/ar_/argo-models/gh_updated.yaml

💊 Project 'argo-models' was not updated for more than 365 days

---

prescriptions/ar_/argh/gh_updated.yaml

💊 Project 'argh' was not updated for more than 365 days

---

prescriptions/ap_/apiclient/gh_updated.yaml

💊 Project 'apiclient' was not updated for more than 365 days

---

README.rst

document on the release of prescriptions
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
/kind documentation
Fixes: https://github.com/thoth-station/prescriptions/issues/18507

document on release of prescriptions

---

prescriptions/ne_/networkx/release_notes.yaml

Move release notes to justification section

---

prescriptions/_containers/ps_cv_ocr/quay_security.yaml
prescriptions/_containers/ps_cv_pytorch/quay_security.yaml
prescriptions/_containers/ps_cv_tensorflow/quay_security.yaml
prescriptions/_containers/ps_ip_ifd/quay_security.yaml
prescriptions/_containers/ps_nlp/quay_security.yaml
prescriptions/_containers/ps_nlp_pytorch/quay_security.yaml
prescriptions/_containers/ps_nlp_tensorflow/quay_security.yaml
prescriptions/_containers/quay_security.yaml
prescriptions/_containers/s2i_custom_notebook/quay_security.yaml
prescriptions/_containers/s2i_custom_py38_notebook/quay_security.yaml
prescriptions/_containers/s2i_elyra_custom_notebook/quay_security.yaml
prescriptions/_containers/s2i_generic_data_science_notebook/quay_security.yaml
prescriptions/_containers/s2i_jupyterbook/quay_security.yaml
prescriptions/_containers/s2i_lab_elyra/quay_security.yaml
prescriptions/_containers/s2i_minimal_notebook/quay_security.yaml
prescriptions/_containers/s2i_minimal_py38_notebook/quay_security.yaml
prescriptions/_containers/s2i_pytorch_notebook/quay_security.yaml
prescriptions/_containers/s2i_scipy_notebook/quay_security.yaml
prescriptions/_containers/s2i_tensorflow_notebook/quay_security.yaml
prescriptions/_containers/s2i_thoth_dev/quay_security.yaml
prescriptions/_containers/s2i_thoth_ubi8_py36/quay_security.yaml
prescriptions/_containers/s2i_thoth_ubi8_py38/quay_security.yaml
prescriptions/_containers/s2i_thoth_ubi8_py39/quay_security.yaml

Fixes: https://github.com/thoth-station/prescriptions-refresh-job/issues/38
Stop the resolution process if the runtime environment has a CVE and secure software should be used.

Stop resolution if recommending secure software and runtime environment has a CVE

---

prescriptions/_security_warnings/builtins.yaml

Related: https://github.com/thoth-station/invectio/issues/107
Related: https://github.com/thoth-station/invectio/pull/109

Produce warnings when exec and eval are used

---

prescriptions/_security_warnings/marshal.yaml

See https://docs.python.org/3/library/marshal.html

Warn about marshal.load and marshal.loads and their security implications

---

prescriptions/de_/defusedxml/xml_recommend.yaml

See https://pypi.org/project/defusedxml/

Recommend using defusedxml to avoid XML specific attacks

---

prescriptions/_security_warnings/popen.yaml

Warn when `os.popen()` and `subprocess.Popen()` are used.

Warn when using os.popen() and subprocess.Popen(shell=True)

---

README.rst

/kind documentation
Fix broken link to prescriptions presentation PDF.

Fix link to prescriptions presentation

---

OWNERS

Add my username to approvers

---

prescriptions/_indexes/aicoe_avx2.yaml

Add prescriptions checking AICoE TF index.

Add prescription for selecting or ignoring AICoE TF index

---

prescriptions/_indexes/aicoe_avx2.yaml
prescriptions/_indexes/pypi.yaml
prescriptions/_indexes/pytorch_cpu.yaml
prescriptions/_indexes/pytorch_cu111.yaml

To have correct types, let's use disabled (string) instead of off (boolean).

Use "disabled" instead of "off" as off is boolean in YAML

---

prescriptions/_generic/cuda_no_gpu.yaml

Related: https://github.com/thoth-station/adviser/pull/2236/

Notify users about no GPU information supplied when CUDA is available

---

prescriptions/sp_/sparsify/tf.yaml

Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>
/kind documentation
Fixes: https://github.com/thoth-station/prescriptions/issues/18518
Link readme to prescription for sparsify

Link readme to prescription for sparsify

---

prescriptions/ne_/netpyne/gh_link.yaml
prescriptions/ri_/rich/gh_link.yaml

Related to https://github.com/thoth-station/prescriptions-refresh-job/issues/117
Update links to project repositories.

Update prescription github links

---

prescriptions/in_/intel-tensorflow/omp_num_threads.yaml
prescriptions/to_/torch/omp_num_threads.yaml

Fix inconsistent schema in advised manifest changes.

Advised manifest changes is a list of objects

---

prescriptions/ji_/jinja2/flask_100.yaml

Related to https://github.com/thoth-station/user-api/issues/1701

jinja2 >=3.0.0 requires flask <=1.0.0

---

prescriptions/py_/pynvx/gh_release_notes.yaml

Organization must be a string

---

prescriptions/_containers/s2i_custom_notebook/quay_security.yaml
prescriptions/_containers/s2i_minimal_notebook/quay_security.yaml
prescriptions/_containers/s2i_minimal_py38_notebook/quay_security.yaml
prescriptions/_containers/s2i_pytorch_notebook/quay_security.yaml
prescriptions/_containers/s2i_thoth_f31_py37/quay_security.yaml
prescriptions/_containers/s2i_thoth_ubi8_py36/quay_security.yaml
prescriptions/_containers/s2i_thoth_ubi8_py38/quay_security.yaml
prescriptions/co_/connexion/werkzeug1x14_connexion2x4x0.yaml
prescriptions/co_/connexion/werkzeug_1x0_2x0.yaml

Related to https://github.com/thoth-station/user-api/issues/1708#issuecomment-1066969750
- No
- No

Cannot install connexion >=2.4.0,<=2.13.0 with werkzeug <0.14

---

prescriptions/_containers/s2i_custom_notebook/quay_security.yaml
prescriptions/_containers/s2i_minimal_notebook/quay_security.yaml
prescriptions/_containers/s2i_minimal_py38_notebook/quay_security.yaml
prescriptions/_containers/s2i_pytorch_notebook/quay_security.yaml
prescriptions/_containers/s2i_thoth_f31_py37/quay_security.yaml
prescriptions/_containers/s2i_thoth_ubi8_py36/quay_security.yaml
prescriptions/_containers/s2i_thoth_ubi8_py38/quay_security.yaml
prescriptions/py_/pynvx/gh_release_notes.yaml

Fix issues in the schema

---

prescriptions/bl_/black/click8x10x0_black.yaml

Related to https://github.com/thoth-station/user-api/pull/1735#pullrequestreview-924543460
- No

Cannot install click==8.10.0 with black<22.3.0

---

prescriptions/is_/iso-639/gh_link.yaml
prescriptions/is_/iso-639/pypi_release.yaml
prescriptions/py_/pynvx/gh_release_notes.yaml

These issues are already known, but we haven't provided fixes for them in prescriptions-refresh job.

Fixes in prescriptions to fix schema validation

---

prescriptions/te_/tensorflow/tf_protobuf4210rc1.yaml

Fixes https://github.com/thoth-station/prescriptions/issues/23112
- No
- No

Add prescription for `tensorflow` and `protobuf==4.21.0-rc1`

---

prescriptions/is_/iso-639/pypi_project_maintainers.yaml
prescriptions/is_/iso-639/pypi_release.yaml
prescriptions/py_/pynvx/gh_release_notes.yaml

We have already discussed these issues, some of them were addressed in prescriptions-refresh-job.

Fixes to make prescriptions loadable in adviser

---

.pre-commit-config.yaml
README.rst

Signed-off-by: Christoph Görn <goern@redhat.com>

turn WHAT into WHY

---

.prow.yaml

Should help with https://github.com/thoth-station/prescriptions-refresh-job/issues/52
This work locally but might not with prow, not sure how their internal git pull
machinery operates.

Run pre-commit only on modified files from PR

---

prescriptions/dj_/dj-database-url/pypi_project_maintainers.yaml

- No
- No
Fixes merge conflict in https://github.com/thoth-station/prescriptions/pull/27829

:pill Project 'dj-database-url' has less than 3 maintainers on PyPI
